# Generated by Django 3.2.21 on 2023-10-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(max_length=120)),
                ('capital', models.CharField(max_length=120)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
